apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-lb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-lb
  template:
    metadata:
      labels:
        app: my-app-lb
    spec:
      containers:
        - name: my-container
          image: nginx:latest
          volumeMounts:
           - name: db-connection
             mountPath: /opt
          ports: 
          - containerPort: 80
      volumes:
        - name: db-connection
          configMap:
            name: test-cm

---
apiVersion: v1
kind: Service
metadata:
  name: my-service-lb
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-app-lb